import Morning from "../../assets/image/morning.png";
import Afternoon from "../../assets/image/afternoon.png";
import Night from "../../assets/image/night.png";
import MorNoon from "../../assets/image/mornoon.jpg";
export const data = [
    {
        userShiftId: 1,
        userId: 1002,
        user: {
            userId: 1002,
            name: "Đỗ Nguyễn Bảo",
            email: "saler1@gmail.com",
            password: "1",
            phone: "0838631706",
            address: "bac",
            dob: null,
            gender: true,
            userImg: "https://rerollcdn.com/characters/Skin/9/Kalista.png",
            roleId: 2,
            isDeleted: false,
            role: {
                roleId: 2,
                name: "saler",
                baseSalary: 20,
                isDeleted: false,
            },
        },
        shiftId: 1,
        shift: {
            shiftId: 1,
            type: "saler-morning",
            startWorkHour: 6,
            endWorkHour: 12,
            coefficient: 1,
        },
        startTime: 1686438000.04,
        endTime: 1686459600.04,
        isHoliday: false,
        isWeekend: true,
        isCheckedIn: null,
        isCheckedOut: null,
        isPaid: true,
        availableEmployees: [
            {
                userId: 3,
                name: "Nguyễn Đức Bảo Vệ",
                email: "saler@gmail.com",
                password: "123",
                phone: "56565",
                address: "111 test street",
                dob: 1052845200000,
                gender: false,
                userImg: "https://rerollcdn.com/characters/Skin/9/Gwen.png",
                roleId: 2,
                isDeleted: false,
                role: {
                    roleId: 2,
                    name: "saler",
                    baseSalary: 20,
                    isDeleted: false,
                },
            },
            {
                userId: 1002,
                name: "Đỗ Nguyễn Bảo",
                email: "saler1@gmail.com",
                password: "1",
                phone: "0838631706",
                address: "bac",
                dob: null,
                gender: true,
                userImg: "https://rerollcdn.com/characters/Skin/9/Kalista.png",
                roleId: 2,
                isDeleted: false,
                role: {
                    roleId: 2,
                    name: "saler",
                    baseSalary: 20,
                    isDeleted: false,
                },
            },
        ],
        date: "11/06/2023",
    },
    {
        userShiftId: 2,
        userId: 3,
        user: {
            userId: 3,
            name: "Nguyễn Đức Bảo Vệ",
            email: "saler@gmail.com",
            password: "123",
            phone: "56565",
            address: "111 test street",
            dob: 1052845200000,
            gender: false,
            userImg: "https://rerollcdn.com/characters/Skin/9/Gwen.png",
            roleId: 2,
            isDeleted: false,
            role: {
                roleId: 2,
                name: "saler",
                baseSalary: 20,
                isDeleted: false,
            },
        },
        shiftId: 2,
        shift: {
            shiftId: 2,
            type: "saler-afternoon",
            startWorkHour: 12,
            endWorkHour: 18,
            coefficient: 1,
        },
        startTime: 1686459600.04,
        endTime: 1686481200.04,
        isHoliday: false,
        isWeekend: true,
        isCheckedIn: null,
        isCheckedOut: null,
        isPaid: true,
        availableEmployees: [
            {
                userId: 3,
                name: "Nguyễn Đức Bảo Vệ",
                email: "saler@gmail.com",
                password: "123",
                phone: "56565",
                address: "111 test street",
                dob: 1052845200000,
                gender: false,
                userImg: "https://rerollcdn.com/characters/Skin/9/Gwen.png",
                roleId: 2,
                isDeleted: false,
                role: {
                    roleId: 2,
                    name: "saler",
                    baseSalary: 20,
                    isDeleted: false,
                },
            },
            {
                userId: 1002,
                name: "Đỗ Nguyễn Bảo",
                email: "saler1@gmail.com",
                password: "1",
                phone: "0838631706",
                address: "bac",
                dob: null,
                gender: true,
                userImg: "https://rerollcdn.com/characters/Skin/9/Kalista.png",
                roleId: 2,
                isDeleted: false,
                role: {
                    roleId: 2,
                    name: "saler",
                    baseSalary: 20,
                    isDeleted: false,
                },
            },
        ],
        date: "11/06/2023",
    },
    {
        userShiftId: 3,
        userId: 1002,
        user: {
            userId: 1002,
            name: "Đỗ Nguyễn Bảo",
            email: "saler1@gmail.com",
            password: "1",
            phone: "0838631706",
            address: "bac",
            dob: null,
            gender: true,
            userImg: "https://rerollcdn.com/characters/Skin/9/Kalista.png",
            roleId: 2,
            isDeleted: false,
            role: {
                roleId: 2,
                name: "saler",
                baseSalary: 20,
                isDeleted: false,
            },
        },
        shiftId: 3,
        shift: {
            shiftId: 3,
            type: "saler-night",
            startWorkHour: 18,
            endWorkHour: 6,
            coefficient: 1.5,
        },
        startTime: 1686481200.04,
        endTime: 1686524400.04,
        isHoliday: false,
        isWeekend: true,
        isCheckedIn: null,
        isCheckedOut: null,
        isPaid: null,
        availableEmployees: [
            {
                userId: 3,
                name: "Nguyễn Đức Bảo Vệ",
                email: "saler@gmail.com",
                password: "123",
                phone: "56565",
                address: "111 test street",
                dob: 1052845200000,
                gender: false,
                userImg: "https://rerollcdn.com/characters/Skin/9/Gwen.png",
                roleId: 2,
                isDeleted: false,
                role: {
                    roleId: 2,
                    name: "saler",
                    baseSalary: 20,
                    isDeleted: false,
                },
            },
            {
                userId: 1002,
                name: "Đỗ Nguyễn Bảo",
                email: "saler1@gmail.com",
                password: "1",
                phone: "0838631706",
                address: "bac",
                dob: null,
                gender: true,
                userImg: "https://rerollcdn.com/characters/Skin/9/Kalista.png",
                roleId: 2,
                isDeleted: false,
                role: {
                    roleId: 2,
                    name: "saler",
                    baseSalary: 20,
                    isDeleted: false,
                },
            },
        ],
        date: "11/06/2023",
    },
    {
        userShiftId: 4,
        userId: 4,
        user: {
            userId: 4,
            name: "guard",
            email: "guard@gmail.com",
            password: "123",
            phone: "56565",
            address: "111 test street",
            dob: 1052845200000,
            gender: true,
            userImg: "https://rerollcdn.com/characters/Skin/9/Kaisa.png",
            roleId: 3,
            isDeleted: false,
            role: {
                roleId: 3,
                name: "guard",
                baseSalary: 15,
                isDeleted: false,
            },
        },
        shiftId: 4,
        shift: {
            shiftId: 4,
            type: "guard-day",
            startWorkHour: 6,
            endWorkHour: 18,
            coefficient: 1,
        },
        startTime: 1686438000.04,
        endTime: 1686481200.04,
        isHoliday: false,
        isWeekend: true,
        isCheckedIn: null,
        isCheckedOut: null,
        isPaid: null,
        availableEmployees: [
            {
                userId: 4,
                name: "guard",
                email: "guard@gmail.com",
                password: "123",
                phone: "56565",
                address: "111 test street",
                dob: 1052845200000,
                gender: true,
                userImg: "https://rerollcdn.com/characters/Skin/9/Kaisa.png",
                roleId: 3,
                isDeleted: false,
                role: {
                    roleId: 3,
                    name: "guard",
                    baseSalary: 15,
                    isDeleted: false,
                },
            },
        ],
        date: "11/06/2023",
    },
    {
        userShiftId: 5,
        userId: 4,
        user: {
            userId: 4,
            name: "guard",
            email: "guard@gmail.com",
            password: "123",
            phone: "56565",
            address: "111 test street",
            dob: 1052845200000,
            gender: true,
            userImg: "https://rerollcdn.com/characters/Skin/9/Kaisa.png",
            roleId: 3,
            isDeleted: false,
            role: {
                roleId: 3,
                name: "guard",
                baseSalary: 15,
                isDeleted: false,
            },
        },
        shiftId: 5,
        shift: {
            shiftId: 5,
            type: "guard-night",
            startWorkHour: 18,
            endWorkHour: 6,
            coefficient: 1.5,
        },
        startTime: 1686481200.04,
        endTime: 1686524400.04,
        isHoliday: false,
        isWeekend: true,
        isCheckedIn: null,
        isCheckedOut: null,
        isPaid: null,
        availableEmployees: [
            {
                userId: 4,
                name: "guard",
                email: "guard@gmail.com",
                password: "123",
                phone: "56565",
                address: "111 test street",
                dob: 1052845200000,
                gender: true,
                userImg: "https://rerollcdn.com/characters/Skin/9/Kaisa.png",
                roleId: 3,
                isDeleted: false,
                role: {
                    roleId: 3,
                    name: "guard",
                    baseSalary: 15,
                    isDeleted: false,
                },
            },
        ],
        date: "11/06/2023",
    },
    {
        userShiftId: 6,
        userId: 3,
        user: {
            userId: 3,
            name: "Nguyễn Đức Bảo Vệ",
            email: "saler@gmail.com",
            password: "123",
            phone: "56565",
            address: "111 test street",
            dob: 1052845200000,
            gender: false,
            userImg: "https://rerollcdn.com/characters/Skin/9/Gwen.png",
            roleId: 2,
            isDeleted: false,
            role: {
                roleId: 2,
                name: "saler",
                baseSalary: 20,
                isDeleted: false,
            },
        },
        shiftId: 1,
        shift: {
            shiftId: 1,
            type: "saler-morning",
            startWorkHour: 6,
            endWorkHour: 12,
            coefficient: 1,
        },
        startTime: 1686524400.04,
        endTime: 1686546000.04,
        isHoliday: false,
        isWeekend: false,
        isCheckedIn: null,
        isCheckedOut: null,
        isPaid: true,
        availableEmployees: [
            {
                userId: 3,
                name: "Nguyễn Đức Bảo Vệ",
                email: "saler@gmail.com",
                password: "123",
                phone: "56565",
                address: "111 test street",
                dob: 1052845200000,
                gender: false,
                userImg: "https://rerollcdn.com/characters/Skin/9/Gwen.png",
                roleId: 2,
                isDeleted: false,
                role: {
                    roleId: 2,
                    name: "saler",
                    baseSalary: 20,
                    isDeleted: false,
                },
            },
            {
                userId: 1002,
                name: "Đỗ Nguyễn Bảo",
                email: "saler1@gmail.com",
                password: "1",
                phone: "0838631706",
                address: "bac",
                dob: null,
                gender: true,
                userImg: "https://rerollcdn.com/characters/Skin/9/Kalista.png",
                roleId: 2,
                isDeleted: false,
                role: {
                    roleId: 2,
                    name: "saler",
                    baseSalary: 20,
                    isDeleted: false,
                },
            },
        ],
        date: "12/06/2023",
    },
    {
        userShiftId: 7,
        userId: 3,
        user: {
            userId: 3,
            name: "Nguyễn Đức Bảo Vệ",
            email: "saler@gmail.com",
            password: "123",
            phone: "56565",
            address: "111 test street",
            dob: 1052845200000,
            gender: false,
            userImg: "https://rerollcdn.com/characters/Skin/9/Gwen.png",
            roleId: 2,
            isDeleted: false,
            role: {
                roleId: 2,
                name: "saler",
                baseSalary: 20,
                isDeleted: false,
            },
        },
        shiftId: 2,
        shift: {
            shiftId: 2,
            type: "saler-afternoon",
            startWorkHour: 12,
            endWorkHour: 18,
            coefficient: 1,
        },
        startTime: 1686546000.04,
        endTime: 1686567600.04,
        isHoliday: false,
        isWeekend: false,
        isCheckedIn: null,
        isCheckedOut: null,
        isPaid: true,
        availableEmployees: [
            {
                userId: 3,
                name: "Nguyễn Đức Bảo Vệ",
                email: "saler@gmail.com",
                password: "123",
                phone: "56565",
                address: "111 test street",
                dob: 1052845200000,
                gender: false,
                userImg: "https://rerollcdn.com/characters/Skin/9/Gwen.png",
                roleId: 2,
                isDeleted: false,
                role: {
                    roleId: 2,
                    name: "saler",
                    baseSalary: 20,
                    isDeleted: false,
                },
            },
            {
                userId: 1002,
                name: "Đỗ Nguyễn Bảo",
                email: "saler1@gmail.com",
                password: "1",
                phone: "0838631706",
                address: "bac",
                dob: null,
                gender: true,
                userImg: "https://rerollcdn.com/characters/Skin/9/Kalista.png",
                roleId: 2,
                isDeleted: false,
                role: {
                    roleId: 2,
                    name: "saler",
                    baseSalary: 20,
                    isDeleted: false,
                },
            },
        ],
        date: "12/06/2023",
    },
    {
        userShiftId: 8,
        userId: 1002,
        user: {
            userId: 1002,
            name: "Đỗ Nguyễn Bảo",
            email: "saler1@gmail.com",
            password: "1",
            phone: "0838631706",
            address: "bac",
            dob: null,
            gender: true,
            userImg: "https://rerollcdn.com/characters/Skin/9/Kalista.png",
            roleId: 2,
            isDeleted: false,
            role: {
                roleId: 2,
                name: "saler",
                baseSalary: 20,
                isDeleted: false,
            },
        },
        shiftId: 3,
        shift: {
            shiftId: 3,
            type: "saler-night",
            startWorkHour: 18,
            endWorkHour: 6,
            coefficient: 1.5,
        },
        startTime: 1686567600.04,
        endTime: 1686610800.04,
        isHoliday: false,
        isWeekend: false,
        isCheckedIn: null,
        isCheckedOut: null,
        isPaid: null,
        availableEmployees: [
            {
                userId: 3,
                name: "Nguyễn Đức Bảo Vệ",
                email: "saler@gmail.com",
                password: "123",
                phone: "56565",
                address: "111 test street",
                dob: 1052845200000,
                gender: false,
                userImg: "https://rerollcdn.com/characters/Skin/9/Gwen.png",
                roleId: 2,
                isDeleted: false,
                role: {
                    roleId: 2,
                    name: "saler",
                    baseSalary: 20,
                    isDeleted: false,
                },
            },
            {
                userId: 1002,
                name: "Đỗ Nguyễn Bảo",
                email: "saler1@gmail.com",
                password: "1",
                phone: "0838631706",
                address: "bac",
                dob: null,
                gender: true,
                userImg: "https://rerollcdn.com/characters/Skin/9/Kalista.png",
                roleId: 2,
                isDeleted: false,
                role: {
                    roleId: 2,
                    name: "saler",
                    baseSalary: 20,
                    isDeleted: false,
                },
            },
        ],
        date: "12/06/2023",
    },
    {
        userShiftId: 9,
        userId: 4,
        user: {
            userId: 4,
            name: "guard",
            email: "guard@gmail.com",
            password: "123",
            phone: "56565",
            address: "111 test street",
            dob: 1052845200000,
            gender: true,
            userImg: "https://rerollcdn.com/characters/Skin/9/Kaisa.png",
            roleId: 3,
            isDeleted: false,
            role: {
                roleId: 3,
                name: "guard",
                baseSalary: 15,
                isDeleted: false,
            },
        },
        shiftId: 4,
        shift: {
            shiftId: 4,
            type: "guard-day",
            startWorkHour: 6,
            endWorkHour: 18,
            coefficient: 1,
        },
        startTime: 1686524400.04,
        endTime: 1686567600.04,
        isHoliday: false,
        isWeekend: false,
        isCheckedIn: null,
        isCheckedOut: null,
        isPaid: null,
        availableEmployees: [
            {
                userId: 4,
                name: "guard",
                email: "guard@gmail.com",
                password: "123",
                phone: "56565",
                address: "111 test street",
                dob: 1052845200000,
                gender: true,
                userImg: "https://rerollcdn.com/characters/Skin/9/Kaisa.png",
                roleId: 3,
                isDeleted: false,
                role: {
                    roleId: 3,
                    name: "guard",
                    baseSalary: 15,
                    isDeleted: false,
                },
            },
        ],
        date: "12/06/2023",
    },
    {
        userShiftId: 10,
        userId: 4,
        user: {
            userId: 4,
            name: "guard",
            email: "guard@gmail.com",
            password: "123",
            phone: "56565",
            address: "111 test street",
            dob: 1052845200000,
            gender: true,
            userImg: "https://rerollcdn.com/characters/Skin/9/Kaisa.png",
            roleId: 3,
            isDeleted: false,
            role: {
                roleId: 3,
                name: "guard",
                baseSalary: 15,
                isDeleted: false,
            },
        },
        shiftId: 5,
        shift: {
            shiftId: 5,
            type: "guard-night",
            startWorkHour: 18,
            endWorkHour: 6,
            coefficient: 1.5,
        },
        startTime: 1686567600.04,
        endTime: 1686610800.04,
        isHoliday: false,
        isWeekend: false,
        isCheckedIn: null,
        isCheckedOut: null,
        isPaid: null,
        availableEmployees: [
            {
                userId: 4,
                name: "guard",
                email: "guard@gmail.com",
                password: "123",
                phone: "56565",
                address: "111 test street",
                dob: 1052845200000,
                gender: true,
                userImg: "https://rerollcdn.com/characters/Skin/9/Kaisa.png",
                roleId: 3,
                isDeleted: false,
                role: {
                    roleId: 3,
                    name: "guard",
                    baseSalary: 15,
                    isDeleted: false,
                },
            },
        ],
        date: "12/06/2023",
    },
    {
        userShiftId: 11,
        userId: null,
        user: null,
        shiftId: 1,
        shift: {
            shiftId: 1,
            type: "saler-morning",
            startWorkHour: 6,
            endWorkHour: 12,
            coefficient: 1,
        },
        startTime: 1686610800.04,
        endTime: 1686632400.04,
        isHoliday: false,
        isWeekend: false,
        isCheckedIn: null,
        isCheckedOut: null,
        isPaid: null,
        availableEmployees: [
            {
                userId: 3,
                name: "Nguyễn Đức Bảo Vệ",
                email: "saler@gmail.com",
                password: "123",
                phone: "56565",
                address: "111 test street",
                dob: 1052845200000,
                gender: false,
                userImg: "https://rerollcdn.com/characters/Skin/9/Gwen.png",
                roleId: 2,
                isDeleted: false,
                role: {
                    roleId: 2,
                    name: "saler",
                    baseSalary: 20,
                    isDeleted: false,
                },
            },
            {
                userId: 1002,
                name: "Đỗ Nguyễn Bảo",
                email: "saler1@gmail.com",
                password: "1",
                phone: "0838631706",
                address: "bac",
                dob: null,
                gender: true,
                userImg: "https://rerollcdn.com/characters/Skin/9/Kalista.png",
                roleId: 2,
                isDeleted: false,
                role: {
                    roleId: 2,
                    name: "saler",
                    baseSalary: 20,
                    isDeleted: false,
                },
            },
        ],
        date: "13/06/2023",
    },
    {
        userShiftId: 12,
        userId: null,
        user: null,
        shiftId: 2,
        shift: {
            shiftId: 2,
            type: "saler-afternoon",
            startWorkHour: 12,
            endWorkHour: 18,
            coefficient: 1,
        },
        startTime: 1686632400.04,
        endTime: 1686654000.04,
        isHoliday: false,
        isWeekend: false,
        isCheckedIn: null,
        isCheckedOut: null,
        isPaid: null,
        availableEmployees: [
            {
                userId: 3,
                name: "Nguyễn Đức Bảo Vệ",
                email: "saler@gmail.com",
                password: "123",
                phone: "56565",
                address: "111 test street",
                dob: 1052845200000,
                gender: false,
                userImg: "https://rerollcdn.com/characters/Skin/9/Gwen.png",
                roleId: 2,
                isDeleted: false,
                role: {
                    roleId: 2,
                    name: "saler",
                    baseSalary: 20,
                    isDeleted: false,
                },
            },
            {
                userId: 1002,
                name: "Đỗ Nguyễn Bảo",
                email: "saler1@gmail.com",
                password: "1",
                phone: "0838631706",
                address: "bac",
                dob: null,
                gender: true,
                userImg: "https://rerollcdn.com/characters/Skin/9/Kalista.png",
                roleId: 2,
                isDeleted: false,
                role: {
                    roleId: 2,
                    name: "saler",
                    baseSalary: 20,
                    isDeleted: false,
                },
            },
        ],
        date: "13/06/2023",
    },
    {
        userShiftId: 13,
        userId: null,
        user: null,
        shiftId: 3,
        shift: {
            shiftId: 3,
            type: "saler-night",
            startWorkHour: 18,
            endWorkHour: 6,
            coefficient: 1.5,
        },
        startTime: 1686654000.04,
        endTime: 1686697200.04,
        isHoliday: false,
        isWeekend: false,
        isCheckedIn: null,
        isCheckedOut: null,
        isPaid: null,
        availableEmployees: [
            {
                userId: 3,
                name: "Nguyễn Đức Bảo Vệ",
                email: "saler@gmail.com",
                password: "123",
                phone: "56565",
                address: "111 test street",
                dob: 1052845200000,
                gender: false,
                userImg: "https://rerollcdn.com/characters/Skin/9/Gwen.png",
                roleId: 2,
                isDeleted: false,
                role: {
                    roleId: 2,
                    name: "saler",
                    baseSalary: 20,
                    isDeleted: false,
                },
            },
            {
                userId: 1002,
                name: "Đỗ Nguyễn Bảo",
                email: "saler1@gmail.com",
                password: "1",
                phone: "0838631706",
                address: "bac",
                dob: null,
                gender: true,
                userImg: "https://rerollcdn.com/characters/Skin/9/Kalista.png",
                roleId: 2,
                isDeleted: false,
                role: {
                    roleId: 2,
                    name: "saler",
                    baseSalary: 20,
                    isDeleted: false,
                },
            },
        ],
        date: "13/06/2023",
    },
    {
        userShiftId: 14,
        userId: null,
        user: null,
        shiftId: 4,
        shift: {
            shiftId: 4,
            type: "guard-day",
            startWorkHour: 6,
            endWorkHour: 18,
            coefficient: 1,
        },
        startTime: 1686610800.04,
        endTime: 1686654000.04,
        isHoliday: false,
        isWeekend: false,
        isCheckedIn: null,
        isCheckedOut: null,
        isPaid: null,
        availableEmployees: [
            {
                userId: 4,
                name: "guard",
                email: "guard@gmail.com",
                password: "123",
                phone: "56565",
                address: "111 test street",
                dob: 1052845200000,
                gender: true,
                userImg: "https://rerollcdn.com/characters/Skin/9/Kaisa.png",
                roleId: 3,
                isDeleted: false,
                role: {
                    roleId: 3,
                    name: "guard",
                    baseSalary: 15,
                    isDeleted: false,
                },
            },
        ],
        date: "13/06/2023",
    },
    {
        userShiftId: 15,
        userId: null,
        user: null,
        shiftId: 5,
        shift: {
            shiftId: 5,
            type: "guard-night",
            startWorkHour: 18,
            endWorkHour: 6,
            coefficient: 1.5,
        },
        startTime: 1686654000.04,
        endTime: 1686697200.04,
        isHoliday: false,
        isWeekend: false,
        isCheckedIn: null,
        isCheckedOut: null,
        isPaid: null,
        availableEmployees: [
            {
                userId: 4,
                name: "guard",
                email: "guard@gmail.com",
                password: "123",
                phone: "56565",
                address: "111 test street",
                dob: 1052845200000,
                gender: true,
                userImg: "https://rerollcdn.com/characters/Skin/9/Kaisa.png",
                roleId: 3,
                isDeleted: false,
                role: {
                    roleId: 3,
                    name: "guard",
                    baseSalary: 15,
                    isDeleted: false,
                },
            },
        ],
        date: "13/06/2023",
    },
    {
        userShiftId: 16,
        userId: null,
        user: null,
        shiftId: 1,
        shift: {
            shiftId: 1,
            type: "saler-morning",
            startWorkHour: 6,
            endWorkHour: 12,
            coefficient: 1,
        },
        startTime: 1686697200.04,
        endTime: 1686718800.04,
        isHoliday: false,
        isWeekend: false,
        isCheckedIn: null,
        isCheckedOut: null,
        isPaid: null,
        availableEmployees: [
            {
                userId: 3,
                name: "Nguyễn Đức Bảo Vệ",
                email: "saler@gmail.com",
                password: "123",
                phone: "56565",
                address: "111 test street",
                dob: 1052845200000,
                gender: false,
                userImg: "https://rerollcdn.com/characters/Skin/9/Gwen.png",
                roleId: 2,
                isDeleted: false,
                role: {
                    roleId: 2,
                    name: "saler",
                    baseSalary: 20,
                    isDeleted: false,
                },
            },
            {
                userId: 1002,
                name: "Đỗ Nguyễn Bảo",
                email: "saler1@gmail.com",
                password: "1",
                phone: "0838631706",
                address: "bac",
                dob: null,
                gender: true,
                userImg: "https://rerollcdn.com/characters/Skin/9/Kalista.png",
                roleId: 2,
                isDeleted: false,
                role: {
                    roleId: 2,
                    name: "saler",
                    baseSalary: 20,
                    isDeleted: false,
                },
            },
        ],
        date: "14/06/2023",
    },
    {
        userShiftId: 17,
        userId: null,
        user: null,
        shiftId: 2,
        shift: {
            shiftId: 2,
            type: "saler-afternoon",
            startWorkHour: 12,
            endWorkHour: 18,
            coefficient: 1,
        },
        startTime: 1686718800.04,
        endTime: 1686740400.04,
        isHoliday: false,
        isWeekend: false,
        isCheckedIn: null,
        isCheckedOut: null,
        isPaid: null,
        availableEmployees: [
            {
                userId: 3,
                name: "Nguyễn Đức Bảo Vệ",
                email: "saler@gmail.com",
                password: "123",
                phone: "56565",
                address: "111 test street",
                dob: 1052845200000,
                gender: false,
                userImg: "https://rerollcdn.com/characters/Skin/9/Gwen.png",
                roleId: 2,
                isDeleted: false,
                role: {
                    roleId: 2,
                    name: "saler",
                    baseSalary: 20,
                    isDeleted: false,
                },
            },
            {
                userId: 1002,
                name: "Đỗ Nguyễn Bảo",
                email: "saler1@gmail.com",
                password: "1",
                phone: "0838631706",
                address: "bac",
                dob: null,
                gender: true,
                userImg: "https://rerollcdn.com/characters/Skin/9/Kalista.png",
                roleId: 2,
                isDeleted: false,
                role: {
                    roleId: 2,
                    name: "saler",
                    baseSalary: 20,
                    isDeleted: false,
                },
            },
        ],
        date: "14/06/2023",
    },
    {
        userShiftId: 18,
        userId: null,
        user: null,
        shiftId: 3,
        shift: {
            shiftId: 3,
            type: "saler-night",
            startWorkHour: 18,
            endWorkHour: 6,
            coefficient: 1.5,
        },
        startTime: 1686740400.04,
        endTime: 1686783600.04,
        isHoliday: false,
        isWeekend: false,
        isCheckedIn: null,
        isCheckedOut: null,
        isPaid: null,
        availableEmployees: [
            {
                userId: 3,
                name: "Nguyễn Đức Bảo Vệ",
                email: "saler@gmail.com",
                password: "123",
                phone: "56565",
                address: "111 test street",
                dob: 1052845200000,
                gender: false,
                userImg: "https://rerollcdn.com/characters/Skin/9/Gwen.png",
                roleId: 2,
                isDeleted: false,
                role: {
                    roleId: 2,
                    name: "saler",
                    baseSalary: 20,
                    isDeleted: false,
                },
            },
            {
                userId: 1002,
                name: "Đỗ Nguyễn Bảo",
                email: "saler1@gmail.com",
                password: "1",
                phone: "0838631706",
                address: "bac",
                dob: null,
                gender: true,
                userImg: "https://rerollcdn.com/characters/Skin/9/Kalista.png",
                roleId: 2,
                isDeleted: false,
                role: {
                    roleId: 2,
                    name: "saler",
                    baseSalary: 20,
                    isDeleted: false,
                },
            },
        ],
        date: "14/06/2023",
    },
];
export const userShifts = [
    {
        id: 1,
        shiftName: "Shift I",
        shiftType: "Morning",
        shiftTime: "6am-12am",
        coefficient: 1,

        shiftImg: Morning,
        pos: "Saler",
    },
    {
        id: 2,
        shiftName: "Shift II",
        shiftType: "Afternoon",
        shiftTime: "12am-6pm",
        coefficient: 1,
        pos: "Saler",
        shiftImg: Afternoon,
    },
    {
        id: 3,
        shiftName: "Shift III",
        shiftType: "Night",
        shiftTime: "6pm-6am",
        coefficient: 1.5,
        pos: "Saler",
        shiftImg: Night,
    },
    {
        id: 4,
        shiftName: "Shift I",
        shiftType: "Morning And Afternoon",
        shiftTime: "6am-6pm",
        coefficient: 1,
        shiftImg: MorNoon,
        pos: "Guard",
    },

    {
        id: 5,
        shiftName: "Shift III",
        shiftType: "Night",
        shiftTime: "6pm-6am",
        coefficient: 1.5,
        pos: "Guard",
        shiftImg: Night,
    },
];

export const instruction = [
    {
        id: 1,
        color: "#ff9683",
        title: "Absent",
    },
    {
        id: 2,
        color: "#adf7b6",
        title: "Present",
    },
    {
        id: 3,
        color: "#ffee93",
        title: "Late",
    },
    {
        id: 4,
        color: "#44cbcd",
        title: "Not yet",
    },
];
export const shiftStatus = {
    alert: {
        data: [
            "not checked in",
            "not checked in and not checked out",
            "not checked in and checked out",
            "not checked in and not checked out",
            "checked in and not checked out",
            "checked in late and not checked out",
        ],
        color: "#ff9683",
    },
    warning: {
        data: [
            "checked in late",
            "checked in late and checked out",
            "checked in and checked out late",
        ],
        color: "#ffee93",
    },
    success: {
        data: ["checked in and checked out", "working"],
        color: "#adf7b6",
    },
    notYet: {
        data: ["not yet"],
        color: "#44cbcd",
    },
};
